apiVersion: backstage.io/v1alpha1
kind: Tool
metadata:
  name: new-dashboard
  displayName: BI Tableau CLI
  description: Command line tool to manage tableau server
  url: https://us-west-2.console.aws.amazon.com/codesuite/codecommit/repositories/bi-cli/setup?region=us-west-2
spec:
  type: tool
  lifecycle: production
  owner: codysj
